name: tests

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: test-latest
    steps:
    - uses: actions/checkout@v2
    - name: test-rules
      uses: returntocorp/semgrep-rules-test-action@master
